<h2>Introduction to Python Numpy</h2>

In [2]:
import numpy as np
from sympy.physics.units import Dimension
from torch.utils.benchmark.utils.fuzzer import dtype_size

In [3]:
print('Introduction to Python Numpy')
# Numpy Tupple 
a = np.array((1, 2, 3,
              4, 5, 6))

print(f"Your Array in Tupple is: {a}")
print(f"The type of array is: {type(a)}") #It reflect the Type of the array weather it is int string or what?



Introduction to Python Numpy
Your Array in Tupple is: [1 2 3 4 5 6]
The type of array is: <class 'numpy.ndarray'>


In [4]:
# Array using List method 
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"Your Array in Tupple is: {a}")
print(f"The type of array is: {type(a)}") #It reflect the Type of the array weather it is int string or what?

Your Array in Tupple is: [[1 2 3]
 [4 5 6]]
The type of array is: <class 'numpy.ndarray'>


<h1>Dimensions of Array</h1>
<h6>1D Array</h6> 
<h6>2D Array</h6>
<h6>3D Array</h4>

In [5]:
#0 Dimensional array
n= np.array(24)
print(f"Your Array in Tuple is: {n}")

print(f"Dimension: ={n.ndim}") # Dimension of array 

Your Array in Tuple is: 24
Dimension: =0


In [6]:
# Now 1 dimensional array
print(f"1 Dimensional Array")
# Array using List method 
a = np.array([1, 2, 3])
print(f"Your 1 dimensional array is: {a}")
print(f"Dimension: ={a.ndim}") # Dimension of array 

1 Dimensional Array
Your 1 dimensional array is: [1 2 3]
Dimension: =1


In [7]:
# Now 2-dimensional array
print(f"1 Dimensional Array")
# Array using List method 
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"Your 2-dimensional array is: {a}")
print(f"Dimension: ={a.ndim}") # Dimension of array 

1 Dimensional Array
Your 2-dimensional array is: [[1 2 3]
 [4 5 6]]
Dimension: =2


<h1>Initialize Numpy Arrays</h1>
Using the zeroes method


In [8]:
#Example 1 for 2 Rows 3 columns
n= np.zeros([2,3])
print(n)
print(type(n))
print(f"Dimension: ={n.ndim}") # Dimension of array 

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
Dimension: =2


In [9]:
#Example 2 1 for 4 Rows 4 columns
n= np.zeros([4,4])
print(n)
print(type(n))
print(f"Dimension: ={n.ndim}") # Dimension of array 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
Dimension: =2


<h3>Data Types</h3>
<h3>b= booleans</h3>
<h3>u= unsigned Integer</h3>
<h3>f= float</h3>
<h3>c= complex float</h3>
<h3>M= datetime</h3>
<h3>O= object</h3>
<h3>S= string</h3>
<h3>U= unicode string</h3>

In [10]:
#Integer Data Type
n= np.array([10, 20, 30])
print(f"The DataType of the array is: {n.dtype}")

The DataType of the array is: int64


In [11]:
#String Data Type
n= np.array(["Amit", "Rohit", "Pushpa", "Virat"])
print(n)
print(f"The DataType of the array is: {n.dtype}")  #Unoicode String is visible here

['Amit' 'Rohit' 'Pushpa' 'Virat']
The DataType of the array is: <U6


In [12]:
#Setup DataType size
n= np.array(["Amit", "Rohit", "Pushpa", "Virat", "Machine"], dtype= 'S5')
print(n.dtype)

|S5


In [13]:
#Convert one data type to another
n= np.array(["10", "20", "30", "40", "50", "60"])
print(n)
print(f"The DataType of the array is: {n.dtype}")

n2= n.astype('i')
print(n2)
print(f"The DataType of the array is: {n2.dtype}")

['10' '20' '30' '40' '50' '60']
The DataType of the array is: <U2
[10 20 30 40 50 60]
The DataType of the array is: int32



<h1>Numpy Array Indexing</h1>
Acces the element from 1st 2bd and 3rd degree array

In [14]:
n=  np.array([10, 20, 30, 40, 50, 60, 70])
print(n[0])


10
